---
version: '3'
services: 
 shub: 
  image: selenium/hub
  ports: 
   - 4444:4444
 schrome: 
  image: selenium/node-chrome-debug
  ports: 
   - 8081:5900  
  links: 
   - shub:shub
 sfirefox: 
  image: selenium/node-firefox-debug
  ports: 
   - 8082:5900
  links: 
   - shub:shub
...
